// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"goal-minder/adapter/repository"
	"goal-minder/domain/usecase"
)

// Injectors from wire.go:

func CreateAccountUsecase() usecase.CreateAccountUsecase {
	accountRepository := repository.NewAccountRepository()
	accountPasswordRepository := repository.NewAccountPasswordRepository()
	createAccountUsecase := usecase.CreateAccountUsecase{
		AccountRepository:         accountRepository,
		AccountPasswordRepository: accountPasswordRepository,
	}
	return createAccountUsecase
}

func LoginUsecase() usecase.LoginUsecase {
	accountPasswordRepository := repository.NewAccountPasswordRepository()
	accountRepository := repository.NewAccountRepository()
	loginUsecase := usecase.LoginUsecase{
		AccountPasswordRepository: accountPasswordRepository,
		AccountRepository:         accountRepository,
	}
	return loginUsecase
}

func MeUsecase() usecase.MeUsecase {
	accountRepository := repository.NewAccountRepository()
	meUsecase := usecase.MeUsecase{
		AccountRepository: accountRepository,
	}
	return meUsecase
}
