// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"goal-minder/adapter/repository"
	"goal-minder/domain/usecase"
)

// Injectors from wire.go:

func CreateAccountUsecase() usecase.CreateAccountUsecase {
	accountRepository := repository.NewAccountRepository()
	accountPasswordRepository := repository.NewAccountPasswordRepository()
	createAccountUsecase := usecase.CreateAccountUsecase{
		AccountRepository:         accountRepository,
		AccountPasswordRepository: accountPasswordRepository,
	}
	return createAccountUsecase
}

func LoginUsecase() usecase.LoginUsecase {
	accountPasswordRepository := repository.NewAccountPasswordRepository()
	loginUsecase := usecase.LoginUsecase{
		AccountPasswordRepository: accountPasswordRepository,
	}
	return loginUsecase
}

func AccountByIDUsecase() usecase.AccountByIDUsecase {
	accountRepository := repository.NewAccountRepository()
	meUsecase := usecase.AccountByIDUsecase{
		AccountRepository: accountRepository,
	}
	return meUsecase
}

func SetGoalUsecase() usecase.SetGoalUsecase {
	accountRepository := repository.NewAccountRepository()
	goalRepository := repository.NewGoalRepository()
	setGoalUsecase := usecase.SetGoalUsecase{
		AccountRepository: accountRepository,
		GoalRepository:    goalRepository,
	}
	return setGoalUsecase
}
