package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	graphql_model "github.com/tanaka-takuto/goal-minder/adapter/graphql/model"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input *graphql_model.LoginInput) (graphql_model.LoginPayload, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}
