package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"context"
	modelContext "goal-minder/domain/context"
)

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	// Cookieの認証トークンをクリアする
	modelContext.GetAuthorizationHelper(ctx).ClearAuthorizationFromCookie()

	return true, nil
}
