package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"context"
	graphql1 "goal-minder/adapter/graphql"
	graphql_model "goal-minder/adapter/graphql/model"
	"goal-minder/adapter/graphql/vo"
	"goal-minder/cmd/di"
	modelContext "goal-minder/domain/context"
	"goal-minder/domain/usecase"
	"goal-minder/infra/db"
)

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*graphql_model.Account, error) {
	account, err := di.MeUsecase().Execute(ctx, db.Con, usecase.MeInput{AccountID: *modelContext.GetAccountID(ctx)})
	if err != nil {
		return nil, err
	}
	return &graphql_model.Account{
		ID:    vo.NewAccountID(account.ID).String(),
		Name:  string(account.Name),
		Email: string(account.Email),
	}, nil
}

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
