package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"context"
	"fmt"
	graphql_model "goal-minder/adapter/graphql/model"
)

// SetGoal is the resolver for the setGoal field.
func (r *mutationResolver) SetGoal(ctx context.Context, input *graphql_model.SetGoalInput) (graphql_model.SetGoaltPayload, error) {
	panic(fmt.Errorf("not implemented: SetGoal - setGoal"))
}
