version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: GM-db
    platform: linux/amd64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=Asia/Tokyo
    environment:
      MYSQL_DATABASE: GM
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/docker-entrypoint-initdb.d
  graphql:
    container_name: GM-graphql
    build:
      context: ./image/graphql
      dockerfile: Dockerfile
    volumes:
      - ../graphql/src:/go/src/goal-minder
    working_dir: /go/src/goal-minder
    tty: true
    environment:
      - ENV=local
      - PORT=3000
      - SECRET_KEY=secret
    ports:
      - 3000:3000
    # command: sh -c 'go mod download && air'
    depends_on:
      - db