output   = "adapter/sqlboiler"
wipe     = true
no-tests = true
add-enum-types = true

[mysql]
  dbname  = "GM"
  host    = "db"
  port    = 3306
  user    = "root"
  pass    = "password"
  sslmode = "false"

[foreign_keys.account_id_fk]
table = "account_password"
column = "account_id"
foreign_table = "account"
foreign_column = "id"
