// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_model

// アプリケーションエラー
type ApplicationError interface {
	IsApplicationError()
	// エラーメッセージ
	GetMessage() string
}

// アカウント作成ペイロード
type CreateAccountPayload interface {
	IsCreateAccountPayload()
}

// ログインペイロード
type LoginPayload interface {
	IsLoginPayload()
}

// アカウント
type Account struct {
	// ID
	ID string `json:"id"`
	// 名前
	Name string `json:"name"`
	// メールアドレス
	Email string `json:"email"`
}

func (Account) IsCreateAccountPayload() {}

func (Account) IsLoginPayload() {}

// アカウント作成インプット
type CreateAccountInput struct {
	// 名前
	Name string `json:"name"`
	// メールアドレス
	Email string `json:"email"`
	// パスワード
	Password string `json:"password"`
}

// 指定されたメールアドレスは既に登録されています
type EmailAlreadyExistsError struct {
	// エラーメッセージ
	Message string `json:"message"`
}

func (EmailAlreadyExistsError) IsApplicationError() {}

// エラーメッセージ
func (this EmailAlreadyExistsError) GetMessage() string { return this.Message }

func (EmailAlreadyExistsError) IsCreateAccountPayload() {}

func (EmailAlreadyExistsError) IsLoginPayload() {}

// ログインインプット
type LoginInput struct {
	// メールアドレス
	Email string `json:"email"`
	// パスワード
	Password string `json:"password"`
}
